version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    depends_on:
      - postgres
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: fram
            password: mwas12345
            migrations: true
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fram
      POSTGRES_PASSWORD: mwas12345
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
